# Урок 4: Работа с модулем NumPy
Добро пожаловать на четвёртый урок по программированию на Python! Сегодня мы познакомимсся с библиотекой **NumPy**.
**NumPy** — это библиотека для языка Python, которая предоставляет удобные и быстрые способы работы с многомерными массивами и матрицами, а также содержит большое количество математических функций для работы с этими массивами. NumPy часто используется в научных вычислениях, анализе данных и машинном обучении.

# 1. Установка NumPy

Для начала работы с NumPy необходимо установить его, если он ещё не установлен. Для этого используйте команду:

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### После установки необходимо перезапустить ядро или просто закрыть-открыть VSCode.

# 2. Импорт библиотеки NumPy

После установки можно импортировать NumPy в программу:

In [1]:
import numpy as np

Здесь `np` — это общепринятое сокращение, чтобы не писать длинное `numpy` в каждой строке кода.

# 3. Основные возможности и функции NumPy

## 3.1. Основным объектом NumPy является **многомерный массив** — `ndarray` (n-dimensional array). Он отличается от стандартных списков Python тем, что:

- Все элементы имеют **одинаковый тип данных** (обычно числа).
- Он позволяет выполнять **векторные операции**, то есть операции над всеми элементами массива одновременно, что значительно ускоряет вычисления.
## Пример создания массивов

In [ ]:
import numpy as np

# Одномерный массив (из списка)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Двумерный массив (матрица)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# Из кортежа
b = np.array((4, 5, 6))
print(b)  # [4 5 6]




## Важные функции для создания массивов:

- **`np.zeros(shape, dtype=float)`**: Создаёт массив, заполненный нулями.

  ```python
  zeros_array = np.zeros((2, 3))
  print(zeros_array)
  # [[0. 0. 0.]
  #  [0. 0. 0.]]
  ```

- **`np.ones(shape, dtype=float)`**: Создаёт массив, заполненный единицами.

  ```python
  ones_array = np.ones((3, 2))
  print(ones_array)
  # [[1. 1.]
  #  [1. 1.]
  #  [1. 1.]]
  ```

- **`np.full(shape, fill_value, dtype=None)`**: Создаёт массив, заполненный заданным значением.

  ```python
  full_array = np.full((2, 2), 7)
  print(full_array)
  # [[7 7]
  #  [7 7]]
  ```

- **`np.eye(N, M=None, k=0, dtype=float)`**: Создаёт единичную матрицу (двумерный массив с единицами на главной диагонали).

  ```python
  identity_matrix = np.eye(3)
  print(identity_matrix)
  # [[1. 0. 0.]
  #  [0. 1. 0.]
  #  [0. 0. 1.]]
  ```

- **`np.arange(start, stop, step, dtype=None)`**: Аналогично встроенной функции `range()`, но возвращает массив.

  ```python
  arr = np.arange(0, 10, 2)
  print(arr)  # [0 2 4 6 8]
  ```

- **`np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)`**: Возвращает равномерно распределённые числа на заданном интервале.

  ```python
  linspace_arr = np.linspace(0, 1, 5)
  print(linspace_arr)  # [0.   0.25 0.5  0.75 1.  ]
  ```

### Параметры функций

- **`shape`**: Кортеж или список, определяющий размерность массива.
- **`dtype`**: Тип данных элементов массива (например, `int`, `float`, `complex`).
- **`start`**: Начальное значение последовательности.
- **`stop`**: Конечное значение последовательности (в `arange` не включается, в `linspace` по умолчанию включается).
- **`step`**: Шаг последовательности.
### Пример:

In [ ]:
import numpy as np

zeros_arr = np.zeros((3, 3))  # Массив из нулей 3x3
ones_arr = np.ones((2, 4))    # Массив из единиц 2x4
range_arr = np.arange(0, 10, 2)  # Чётные числа от 0 до 10
linspace_arr = np.linspace(0, 1, 5)  # 5 значений от 0 до 1

print(zeros_arr)
print(ones_arr)
print(range_arr)
print(linspace_arr)

## Типы данных в NumPy

NumPy поддерживает различные типы данных:

- **`int`**: Целые числа (`int8`, `int16`, `int32`, `int64`).
- **`float`**: Числа с плавающей точкой (`float16`, `float32`, `float64`).
- **`complex`**: Комплексные числа (`complex64`, `complex128`).
- **`bool`**: Логический тип данных (`True` или `False`).
- **`string`** и **`unicode`**: Строковые типы данных.

### Задание типа данных

При создании массива можно явно указать тип данных с помощью параметра `dtype`:

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  # float32

## 3.2. Индексация и срезы

NumPy позволяет легко получать доступ к элементам массива или его частям с помощью индексации и срезов.

### Пример индексации:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Получение элемента по индексу
print(arr[0])  # 10
print(arr[3])  # 40

### Пример срезов:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Получаем элементы с 2-го по 4-й (индексы 1, 2, 3)
print(arr[1:4])  # [2, 3, 4]

# Получаем элементы с 3-го до конца
print(arr[2:])  # [3, 4, 5, 6, 7]

### Логическая индексация

Можно использовать логические условия для выборки элементов массива.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Выбрать элементы больше 3
condition = arr > 3
print(condition)   # [False False False  True  True]
print(arr[condition])  # [4 5]

## 3.3. Изменение формы массива


### Функция `reshape()`

Метод **`reshape()`** позволяет изменить форму массива без изменения его данных.

```python
arr = np.arange(6)
print(arr)  # [0 1 2 3 4 5]

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# [[0 1 2]
#  [3 4 5]]
```

### Параметры функции `reshape()`

- **`newshape`**: Новая форма массива, заданная кортежем. Произведение размеров должно совпадать с числом элементов в массиве.

### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Превращаем одномерный массив в двумерный массив 2x3
reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)

## 3.4. Математические операции

NumPy поддерживает арифметические операции над массивами поэлементно.


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Сложение массивов
print(arr1 + arr2)  # [5 7 9]

# Умножение массива на число
print(arr1 * 2)  # [2 4 6]

# Возведение массива в степень
print(arr1 ** 2)  # [1 4 9]

### Универсальные функции (ufunc)

NumPy предоставляет большое количество математических функций, применяемых поэлементно.



### Параметры функций

- **`np.sin(x)`**: Синус каждого элемента массива `x`.
- **`np.cos(x)`**: Косинус каждого элемента массива `x`.
- **`np.exp(x)`**: Экспонента каждого элемента массива `x`.
- **`np.sqrt(x)`**: Квадратный корень каждого элемента массива `x`.
- **`np.log(x)`**: Натуральный логарифм каждого элемента массива `x`.

In [ ]:
arr = np.array([0, np.pi / 2, np.pi])

print(np.sin(arr))  # [0.000000e+00 1.000000e+00 1.224646e-16]
print(np.cos(arr))  # [ 1.000000e+00  6.123234e-17 -1.000000e+00]
print(np.exp(arr))  # [ 1.          4.81047738 23.14069263]

## 3.5. Операции с матрицами

NumPy предоставляет функции для выполнения матричных операций.

### Пример умножения матриц:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Матричное умножение
C = np.dot(A, B)
print(C)

## 3.6. Статистические функции

NumPy содержит много встроенных статистических функций.


### Основные функции

- **`np.min(a, axis=None)`**: Минимальное значение массива `a`.
- **`np.max(a, axis=None)`**: Максимальное значение массива `a`.
- **`np.mean(a, axis=None)`**: Среднее значение элементов массива `a`.
- **`np.median(a, axis=None)`**: Медиана элементов массива `a`.
- **`np.std(a, axis=None)`**: Стандартное отклонение элементов массива `a`.
- **`np.var(a, axis=None)`**: Дисперсия элементов массива `a`.
- **`np.sum(a, axis=None)`**: Сумма элементов массива `a`.



### Параметр `axis`

- **`axis=0`**: Операция выполняется по столбцам.
- **`axis=1`**: Операция выполняется по строкам.
### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Среднее значение
print(np.mean(arr))  # 3.0

# Стандартное отклонение
print(np.std(arr))  # 1.414

# Максимум и минимум
print(np.max(arr))  # 5
print(np.min(arr))  # 1


arr1 = np.array([[1, 2], [3, 4]])
print(np.sum(arr1, axis=0))  # [4 6]
print(np.sum(arr1, axis=1))  # [3 7]

## 3.7. Генерация случайных чисел


- **`np.random.rand(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из равномерного распределения на интервале [0, 1).

```python
random_arr = np.random.rand(3, 2)
print(random_arr)
```

- **`np.random.randn(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из стандартного нормального распределения.

```python
normal_arr = np.random.randn(3, 3)
print(normal_arr)
```

- **`np.random.randint(low, high=None, size=None, dtype=int)`**: Возвращает случайные целые числа из заданного интервала.

```python
int_arr = np.random.randint(1, 10, size=(2, 2))
print(int_arr)
```

### Параметры функций

- **`low`**: Нижняя граница (включительно).
- **`high`**: Верхняя граница (исключительно).
- **`size`**: Размер выходного массива.
- **`d0, d1, ..., dn`**: Размерности выходного массива.

### Пример:

In [2]:
random_arr = np.random.rand(3, 3)
print(random_arr)

random_int_arr = np.random.randint(1, 10, size=(2, 3))
print(random_int_arr)

normal_arr = np.random.randn(3, 3)
print(normal_arr)

[[0.96378206 0.87177143 0.98229712]
 [0.43556971 0.5656304  0.68631937]
 [0.65288572 0.09160212 0.392808  ]]
[[7 7 2]
 [7 1 7]]
[[-0.01256177 -0.51337175 -0.59110316]
 [ 0.02422629  0.89622877 -0.49134698]
 [-0.38665931 -0.42791214  2.46081699]]


## Линейная алгебра

NumPy содержит модуль `numpy.linalg` для выполнения операций линейной алгебры.


### Основные функции


- **`np.dot(a, b)`**: Матричное умножение массивов `a` и `b`.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
  
print(np.dot(a, b))
# [[19 22]
#  [43 50]]

- **`np.transpose(a)`** или `a.T`: Транспонирование массива `a`.

In [ ]:
print(a.T)
# [[1 3]
#  [2 4]]

- **`np.linalg.inv(a)`**: Обратная матрица для массива `a`.

In [ ]:
inv_a = np.linalg.inv(a)
print(inv_a)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

- **`np.linalg.det(a)`**: Детерминант массива `a`.

In [ ]:

det_a = np.linalg.det(a)
print(det_a)  # -2.0000000000000004

- **`np.linalg.eig(a)`**: Собственные значения и собственные векторы массива `a`.

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Собственные значения:", eigenvalues)
print("Собственные векторы:", eigenvectors)

#### Параметры функций

- **`a`, `b`**: Входные массивы (матрицы).
- **`axis`**: Ось, по которой выполняется операция.

# 4. Полезные функции и методы

### Функция `np.where(condition, [x, y])`

Возвращает элементы из `x`, где условие `condition` истинно, и элементы из `y` — где ложно.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

result = np.where(arr > 3, arr, 0)
print(result)  # [0 0 0 4 5]

### Функция `np.concatenate((a1, a2, ...), axis=0)`

Объединяет массивы вдоль указанной оси.


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

concat_arr = np.concatenate((a, b))
print(concat_arr)  # [1 2 3 4]

### Функция `np.unique(ar, return_counts=False)`

Находит уникальные элементы массива.
Если установить `return_counts=True`, то функция также вернёт количество вхождений каждого элемента.

In [ ]:
arr = np.array([1, 2, 2, 3, 3, 3])

unique_elements = np.unique(arr)
print(unique_elements)  # [1 2 3]

### Функция `np.triu(m,k)`

Функция numpy.triu (Triangle Upper) возвращает верхний треугольник двумерного массива или матрицы. Это означает, что она сохраняет элементы на главной диагонали и выше, а элементы ниже главной диагонали заменяет на нули (или на другое заданное значение).
### Параметры

- **`m`**: Входной массив или матрица, для которой нужно получить верхний треугольник.

- **`k`**: - Диагональ, относительно которой определяется верхний треугольник.
  - По умолчанию `k=0`, что означает главную диагональ.
  - `k > 0`: диагональ выше главной.
  - `k < 0`: диагональ ниже главной.


In [3]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Получаем верхний треугольник
upper_triangle = np.triu(a)

print("Оригинальная матрица:")
print(a)

print("\nВерхний треугольник матрицы:")
print(upper_triangle)

Оригинальная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Верхний треугольник матрицы:
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]



- **Документация NumPy**: [https://numpy.org/doc/](https://numpy.org/doc/)

# Задания для закрепления материала

# Задание №1. Нормализация массива с фильтрацией
**Описание**: Создайте массив случайных чисел размером 5x5. Затем отфильтруйте числа, которые больше среднего значения этого массива, и нормализуйте их так, чтобы сумма оставшихся элементов равнялась 1.


In [ ]:
# TODO

# Задание №2. Нахождение максимума в каждом ряду
**Описание**: Создайте двумерный массив размером 5x5 с произвольными числами. Пройдитесь по каждому ряду и найдите максимальное значение. Если максимальное значение больше 10, замените все элементы этого ряда на 1.

In [ ]:
# TODO

# Задание №3. Создание симметричной матрицы
**Описание**: Создайте случайную матрицу 4x4 и преобразуйте её в симметричную (где элемент [i, j] равен элементу [j, i]). Если элемент на диагонали меньше 0, замените его на 0.

In [ ]:
# TODO

# Задание №4. Кумулятивная сумма с проверкой
**Описание**: Создайте массив из 10 случайных чисел. Рассчитайте кумулятивную сумму. Если на каком-либо шаге кумулятивная сумма превышает 50, прекратите вычисления и выведите позицию, на которой произошло превышение.

In [ ]:
# TODO

# Задание №5. Создание единичной матрицы с модификацией
**Описание**: Создайте единичную матрицу размером 5x5. Если элемент на главной диагонали является нечётным числом, замените его на 2.

In [ ]:
# TODO

# Задание №6. Матричное умножение с проверкой
**Описание**: Создайте две случайные матрицы 3x3 и выполните их матричное умножение. Если сумма любого столбца в результирующей матрице больше 15, замените все элементы этого столбца на -1.

In [ ]:
# TODO

# Задание №7. Нахождение уникальных значений с фильтрацией
**Описание**: Создайте массив случайных чисел. Найдите уникальные элементы. Если количество уникальных элементов больше 10, удалите все числа, которые больше 50.

In [ ]:
# TODO

# Задание №8. Модификация массива на основе медианы
**Описание**: Создайте массив случайных чисел размером 1x10. Найдите медиану массива. Если число больше медианы, умножьте его на 2, если меньше — поделите на 2.

In [ ]:
# TODO

# Задание №9. Отбор элементов с фильтрацией и умножением
**Описание**: Создайте двумерный массив размером 5x5. Отберите все элементы, которые являются чётными и больше среднего значения массива, и умножьте их на 3.

In [ ]:
# TODO

# Задание №10. Поэлементное сложение с условиями
**Описание**: Создайте два одномерных массива по 10 элементов каждый. Выполните поэлементное сложение. Если сумма элементов на каком-то шаге превышает 10, замените этот элемент на 0.

In [ ]:
# TODO

# Задание №11.  Сортировка и фильтрация массива
**Описание**: Создайте массив случайных чисел. Отсортируйте его по возрастанию. Затем найдите все элементы, которые меньше среднего значения массива, и замените их на 0.

In [ ]:
# TODO

# Задание №12.  Транспонирование с модификацией
**Описание**: Создайте двумерный массив 3x3. Транспонируйте его и замените все элементы, которые больше 5, на их логарифмы.

In [ ]:
# TODO

# Задание №13.  Обратная матрица с проверкой
**Описание**: Создайте случайную матрицу 3x3. Найдите её обратную матрицу. Если сумма какого-либо ряда в обратной матрице больше 10, умножьте этот ряд на 2.

In [ ]:
# TODO

# Задание №14. Перемешивание с модификацией
**Описание**: Создайте массив из 10 чисел. Перемешайте элементы массива случайным образом. Если в новом массиве есть числа больше 5, уменьшите их на 3.

In [ ]:
# TODO

# Задание №15.  Цикл с вложенным условием
**Описание**: Создайте двумерный массив 4x4. Для каждого элемента массива выполните следующее: если элемент чётный, возведите его в квадрат, если нечётный — умножьте на 2.

In [ ]:
# TODO