# Урок 4: Работа с модулем NumPy
Добро пожаловать на четвёртый урок по программированию на Python! Сегодня мы познакомимсся с библиотекой **NumPy**.
**NumPy** — это библиотека для языка Python, которая предоставляет удобные и быстрые способы работы с многомерными массивами и матрицами, а также содержит большое количество математических функций для работы с этими массивами. NumPy часто используется в научных вычислениях, анализе данных и машинном обучении.

# 1. Установка NumPy

Для начала работы с NumPy необходимо установить его, если он ещё не установлен. Для этого используйте команду:

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### После установки необходимо перезапустить ядро или просто закрыть-открыть VSCode.

# 2. Импорт библиотеки NumPy

После установки можно импортировать NumPy в программу:

In [1]:
import numpy as np

Здесь `np` — это общепринятое сокращение, чтобы не писать длинное `numpy` в каждой строке кода.

# 3. Основные возможности и функции NumPy

## 3.1. Основным объектом NumPy является **многомерный массив** — `ndarray` (n-dimensional array). Он отличается от стандартных списков Python тем, что:

- Все элементы имеют **одинаковый тип данных** (обычно числа).
- Он позволяет выполнять **векторные операции**, то есть операции над всеми элементами массива одновременно, что значительно ускоряет вычисления.
## Пример создания массивов

In [2]:
import numpy as np

# Одномерный массив (из списка)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Двумерный массив (матрица)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# Из кортежа
b = np.array((4, 5, 6))
print(b)  # [4 5 6]




[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[4 5 6]


## Важные функции для создания массивов:

- **`np.zeros(shape, dtype=float)`**: Создаёт массив, заполненный нулями.

  ```python
  zeros_array = np.zeros((2, 3))
  print(zeros_array)
  # [[0. 0. 0.]
  #  [0. 0. 0.]]
  ```

- **`np.ones(shape, dtype=float)`**: Создаёт массив, заполненный единицами.

  ```python
  ones_array = np.ones((3, 2))
  print(ones_array)
  # [[1. 1.]
  #  [1. 1.]
  #  [1. 1.]]
  ```

- **`np.full(shape, fill_value, dtype=None)`**: Создаёт массив, заполненный заданным значением.

  ```python
  full_array = np.full((2, 2), 7)
  print(full_array)
  # [[7 7]
  #  [7 7]]
  ```

- **`np.eye(N, M=None, k=0, dtype=float)`**: Создаёт единичную матрицу (двумерный массив с единицами на главной диагонали).

  ```python
  identity_matrix = np.eye(3)
  print(identity_matrix)
  # [[1. 0. 0.]
  #  [0. 1. 0.]
  #  [0. 0. 1.]]
  ```

- **`np.arange(start, stop, step, dtype=None)`**: Аналогично встроенной функции `range()`, но возвращает массив.

  ```python
  arr = np.arange(0, 10, 2)
  print(arr)  # [0 2 4 6 8]
  ```

- **`np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)`**: Возвращает равномерно распределённые числа на заданном интервале.

  ```python
  linspace_arr = np.linspace(0, 1, 5)
  print(linspace_arr)  # [0.   0.25 0.5  0.75 1.  ]
  ```

### Параметры функций

- **`shape`**: Кортеж или список, определяющий размерность массива.
- **`dtype`**: Тип данных элементов массива (например, `int`, `float`, `complex`).
- **`start`**: Начальное значение последовательности.
- **`stop`**: Конечное значение последовательности (в `arange` не включается, в `linspace` по умолчанию включается).
- **`step`**: Шаг последовательности.
### Пример:

In [51]:
import numpy as np

zeros_arr = np.zeros((3, 3))  # Массив из нулей 3x3
ones_arr = np.ones((2, 4))    # Массив из единиц 2x4
range_arr = np.arange(0, 10, 2)  # Чётные числа от 0 до 10
linspace_arr = np.linspace(0, 1, 5)  # 5 значений от 0 до 1

print(zeros_arr)
print(ones_arr)
print(range_arr)
print(linspace_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Типы данных в NumPy

NumPy поддерживает различные типы данных:

- **`int`**: Целые числа (`int8`, `int16`, `int32`, `int64`).
- **`float`**: Числа с плавающей точкой (`float16`, `float32`, `float64`).
- **`complex`**: Комплексные числа (`complex64`, `complex128`).
- **`bool`**: Логический тип данных (`True` или `False`).
- **`string`** и **`unicode`**: Строковые типы данных.

### Задание типа данных

При создании массива можно явно указать тип данных с помощью параметра `dtype`:

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  # float32

## 3.2. Индексация и срезы

NumPy позволяет легко получать доступ к элементам массива или его частям с помощью индексации и срезов.

### Пример индексации:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Получение элемента по индексу
print(arr[0])  # 10
print(arr[3])  # 40

### Пример срезов:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Получаем элементы с 2-го по 4-й (индексы 1, 2, 3)
print(arr[1:4])  # [2, 3, 4]

# Получаем элементы с 3-го до конца
print(arr[2:])  # [3, 4, 5, 6, 7]

### Логическая индексация

Можно использовать логические условия для выборки элементов массива.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Выбрать элементы больше 3
condition = arr > 3
print(condition)   # [False False False  True  True]
print(arr[condition])  # [4 5]

## 3.3. Изменение формы массива


### Функция `reshape()`

Метод **`reshape()`** позволяет изменить форму массива без изменения его данных.

```python
arr = np.arange(6)
print(arr)  # [0 1 2 3 4 5]

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# [[0 1 2]
#  [3 4 5]]
```

### Параметры функции `reshape()`

- **`newshape`**: Новая форма массива, заданная кортежем. Произведение размеров должно совпадать с числом элементов в массиве.

### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Превращаем одномерный массив в двумерный массив 2x3
reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)

## 3.4. Математические операции

NumPy поддерживает арифметические операции над массивами поэлементно.


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Сложение массивов
print(arr1 + arr2)  # [5 7 9]

# Умножение массива на число
print(arr1 * 2)  # [2 4 6]

# Возведение массива в степень
print(arr1 ** 2)  # [1 4 9]

### Универсальные функции (ufunc)

NumPy предоставляет большое количество математических функций, применяемых поэлементно.



### Параметры функций

- **`np.sin(x)`**: Синус каждого элемента массива `x`.
- **`np.cos(x)`**: Косинус каждого элемента массива `x`.
- **`np.exp(x)`**: Экспонента каждого элемента массива `x`.
- **`np.sqrt(x)`**: Квадратный корень каждого элемента массива `x`.
- **`np.log(x)`**: Натуральный логарифм каждого элемента массива `x`.

In [ ]:
arr = np.array([0, np.pi / 2, np.pi])

print(np.sin(arr))  # [0.000000e+00 1.000000e+00 1.224646e-16]
print(np.cos(arr))  # [ 1.000000e+00  6.123234e-17 -1.000000e+00]
print(np.exp(arr))  # [ 1.          4.81047738 23.14069263]

## 3.5. Операции с матрицами

NumPy предоставляет функции для выполнения матричных операций.

### Пример умножения матриц:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Матричное умножение
C = np.dot(A, B)
print(C)

## 3.6. Статистические функции

NumPy содержит много встроенных статистических функций.


### Основные функции

- **`np.min(a, axis=None)`**: Минимальное значение массива `a`.
- **`np.max(a, axis=None)`**: Максимальное значение массива `a`.
- **`np.mean(a, axis=None)`**: Среднее значение элементов массива `a`.
- **`np.median(a, axis=None)`**: Медиана элементов массива `a`.
- **`np.std(a, axis=None)`**: Стандартное отклонение элементов массива `a`.
- **`np.var(a, axis=None)`**: Дисперсия элементов массива `a`.
- **`np.sum(a, axis=None)`**: Сумма элементов массива `a`.



### Параметр `axis`

- **`axis=0`**: Операция выполняется по столбцам.
- **`axis=1`**: Операция выполняется по строкам.
### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Среднее значение
print(np.mean(arr))  # 3.0

# Стандартное отклонение
print(np.std(arr))  # 1.414

# Максимум и минимум
print(np.max(arr))  # 5
print(np.min(arr))  # 1


arr1 = np.array([[1, 2], [3, 4]])
print(np.sum(arr1, axis=0))  # [4 6]
print(np.sum(arr1, axis=1))  # [3 7]

## 3.7. Генерация случайных чисел


- **`np.random.rand(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из равномерного распределения на интервале [0, 1).

```python
random_arr = np.random.rand(3, 2)
print(random_arr)
```

- **`np.random.randn(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из стандартного нормального распределения.

```python
normal_arr = np.random.randn(3, 3)
print(normal_arr)
```

- **`np.random.randint(low, high=None, size=None, dtype=int)`**: Возвращает случайные целые числа из заданного интервала.

```python
int_arr = np.random.randint(1, 10, size=(2, 2))
print(int_arr)
```

### Параметры функций

- **`low`**: Нижняя граница (включительно).
- **`high`**: Верхняя граница (исключительно).
- **`size`**: Размер выходного массива.
- **`d0, d1, ..., dn`**: Размерности выходного массива.

### Пример:

In [3]:
random_arr = np.random.rand(3, 3)
print(random_arr)

random_int_arr = np.random.randint(1, 10, size=(2, 3))
print(random_int_arr)

normal_arr = np.random.randn(3, 3)
print(normal_arr)

[[0.70955173 0.56753979 0.07881106]
 [0.221642   0.93480598 0.70655663]
 [0.79121971 0.40487305 0.97785112]]
[[4 8 7]
 [8 6 2]]
[[-0.57141165  1.6980575   0.58449901]
 [ 0.38504758  0.40432412  0.93357419]
 [ 0.73086272  0.61757235 -0.58753044]]


## Линейная алгебра

NumPy содержит модуль `numpy.linalg` для выполнения операций линейной алгебры.


### Основные функции


- **`np.dot(a, b)`**: Матричное умножение массивов `a` и `b`.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
  
print(np.dot(a, b))
# [[19 22]
#  [43 50]]

- **`np.transpose(a)`** или `a.T`: Транспонирование массива `a`.

In [ ]:
print(a.T)
# [[1 3]
#  [2 4]]

- **`np.linalg.inv(a)`**: Обратная матрица для массива `a`.

In [ ]:
inv_a = np.linalg.inv(a)
print(inv_a)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

- **`np.linalg.det(a)`**: Детерминант массива `a`.

In [ ]:

det_a = np.linalg.det(a)
print(det_a)  # -2.0000000000000004

- **`np.linalg.eig(a)`**: Собственные значения и собственные векторы массива `a`.

In [18]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Собственные значения:", eigenvalues)
print("Собственные векторы:", eigenvectors)

Собственные значения: [ 9.36722315 -0.70755601 -1.65966714]
Собственные векторы: [[-0.64751489 -0.79726288 -0.42924834]
 [-0.48163609  0.57604544 -0.35142838]
 [-0.59055156 -0.18039833  0.83201199]]


#### Параметры функций

- **`a`, `b`**: Входные массивы (матрицы).
- **`axis`**: Ось, по которой выполняется операция.

# 4. Полезные функции и методы

### Функция `np.where(condition, [x, y])`

Возвращает элементы из `x`, где условие `condition` истинно, и элементы из `y` — где ложно.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

result = np.where(arr > 3, arr, 0)
print(result)  # [0 0 0 4 5]

### Функция `np.concatenate((a1, a2, ...), axis=0)`

Объединяет массивы вдоль указанной оси.


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

concat_arr = np.concatenate((a, b))
print(concat_arr)  # [1 2 3 4]

### Функция `np.unique(ar, return_counts=False)`

Находит уникальные элементы массива.
Если установить `return_counts=True`, то функция также вернёт количество вхождений каждого элемента.

In [ ]:
arr = np.array([1, 2, 2, 3, 3, 3])

unique_elements = np.unique(arr)
print(unique_elements)  # [1 2 3]

### Функция `np.triu(m,k)`

Функция numpy.triu (Triangle Upper) возвращает верхний треугольник двумерного массива или матрицы. Это означает, что она сохраняет элементы на главной диагонали и выше, а элементы ниже главной диагонали заменяет на нули (или на другое заданное значение).
### Параметры

- **`m`**: Входной массив или матрица, для которой нужно получить верхний треугольник.

- **`k`**: - Диагональ, относительно которой определяется верхний треугольник.
  - По умолчанию `k=0`, что означает главную диагональ.
  - `k > 0`: диагональ выше главной.
  - `k < 0`: диагональ ниже главной.


In [3]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Получаем верхний треугольник
upper_triangle = np.triu(a)

print("Оригинальная матрица:")
print(a)

print("\nВерхний треугольник матрицы:")
print(upper_triangle)

Оригинальная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Верхний треугольник матрицы:
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]



- **Документация NumPy**: [https://numpy.org/doc/](https://numpy.org/doc/)

# Задания для закрепления материала

# Задание №1.  **Нахождение максимального элемента**
**Описание**: Создайте случайный одномерный массив из 10 элементов и найдите максимальное значение.  
**Подсказка**: Используйте `np.random.rand()` и `np.max()`.

In [5]:
import numpy as np

a = np.random.rand(10)
print('Исходный массив:', a)
print('Максимальное значение:', np.max(a))

Исходный массив: [0.70795157 0.78961419 0.03725983 0.61931413 0.77997826 0.4518458
 0.62504199 0.81706608 0.91150493 0.63162403]
Максимальное значение: 0.9115049303560041


# Задание №2. **Обратная матрица**
**Описание**: Создайте квадратную матрицу 3x3 и найдите её обратную матрицу.  
**Подсказка**: Используйте `np.linalg.inv()`.


In [12]:
import numpy as np

a = np.random.randint(1, 10, size = (3,3))
print('Исходная матрица:')
print(a)
print('Обратная матрица:')
print( np.linalg.inv(a)) 



Исходная матрица:
[[6 1 4]
 [6 9 1]
 [8 9 8]]
Обратная матрица:
[[ 0.23684211  0.10526316 -0.13157895]
 [-0.15037594  0.06015038  0.06766917]
 [-0.06766917 -0.17293233  0.18045113]]


# Задание №3. **Матричное умножение**
**Описание**: Создайте две матрицы 2x2 и выполните их матричное умножение.  
**Подсказка**: Используйте функцию `np.dot()`.

In [14]:
import numpy as np

a = np.random.randint(1, 10, size = (2,2))
b = np.random.randint(1, 10, size = (2,2))

print('Матрица A:')
print(a)
print('Матрица B:')
print(b)
print('A x B:')
print(np.dot(a,b))

Матрица A:
[[1 9]
 [9 3]]
Матрица B:
[[5 5]
 [2 1]]
A x B:
[[23 14]
 [51 48]]


# Задание №4. **Нахождение собственных значений**
**Описание**: Создайте матрицу 3x3 и найдите её собственные значения.  
**Подсказка**: Используйте функцию `np.linalg.eig()`.

In [19]:
import numpy as np

a = np.random.randint(1, 10, size = (3,3))
print('Исходная матрица:')
print(a)
print('Собственные числа:')
l,_ = np.linalg.eig(a)
print(*l) 

Исходная матрица:
[[6 9 6]
 [6 6 2]
 [4 2 2]]
Собственные числа:
15.188382766488473 -2.668667478405733 1.4802847119172748


# Задание №5. **Умножение матриц на вектор**
**Описание**: Создайте матрицу 3x3 и вектор из 3 элементов, выполните их умножение.  
**Подсказка**: Используйте `np.dot()`.

In [23]:
import numpy as np

a = np.random.randint(1, 10, size = (3,3))
b = np.random.randint(1, 10, size = (3))

print('Матрица A:')
print(a)
print('Вектор B:')
print(b)
print('A x B:')
print(np.dot(a,b))

Матрица A:
[[9 5 2]
 [8 2 3]
 [9 8 8]]
Вектор B:
[4 2 3]
A x B:
[52 45 76]


# Задание №6. **Сумма элементов по строкам и столбцам**
**Описание**: Создайте случайную матрицу 4x4 и найдите сумму элементов каждой строки и каждого столбца.  
**Подсказка**: Используйте `np.sum()` с параметром `axis`.

In [25]:
import numpy as np

a = np.random.randint(1, 10, size = (4,4))

print('Матрица A:')
print(a)
print('Сумма в каждой строке')
print(np.sum(a, axis = 1))
print('Сумма в каждом столбце')
print(np.sum(a, axis = 0))

Матрица A:
[[6 9 6 1]
 [4 1 5 8]
 [9 2 6 8]
 [4 4 9 2]]
Сумма в каждой строке
[22 18 25 19]
Сумма в каждом столбце
[23 16 26 19]


# Задание №7. **Медиана каждой строки матрицы**
**Описание**: Создайте случайную матрицу 5x5 и найдите медиану каждого ряда (строки).  
**Подсказка**: Используйте `np.median()` с параметром `axis`.

In [41]:
import numpy as np

a = np.random.randint(1, 10, size = (5,5))

print('Матрица A:')
print(a)
print('Медиана в каждой строке')
print(np.median(a, axis = 1))


Матрица A:
[[8 4 6 7 5]
 [7 5 5 5 3]
 [7 8 9 2 1]
 [7 4 9 5 4]
 [9 6 5 9 3]]
Медиана в каждой строке
[6. 5. 7. 5. 6.]


# Задание №8. **Нахождение элементов по условию**
**Описание**: Создайте массив из 10 элементов и найдите все элементы, которые больше среднего значения массива.  
**Подсказка**: Используйте условие для массива.

In [42]:
a = np.random.randint(1, 10, size = (10))

print('Массив:')
print(a)
s = np.median(a)
print('Среднее значение', s)
print('Элементы больше сред знач:')
print(a[a>s])


Массив:
[8 4 2 4 4 1 3 7 9 5]
Среднее значение 4.0
Элементы больше сред знач:
[8 7 9 5]


# Задание №9. **Поэлементное умножение массивов**
**Описание**: Создайте два массива одинакового размера и выполните их поэлементное умножение.  
**Подсказка**: Используйте операцию умножения `*`.

In [45]:
import numpy as np

a = np.random.randint(1, 10, size = (3))
b = np.random.randint(1, 10, size = (3))

print('Массив A:')
print(a)
print('Массив B:')
print(b)
print('A * B:')
print(a*b)

Массив A:
[8 5 5]
Массив B:
[9 7 8]
A * B:
[72 35 40]


# Задание №10. **Формирование матрицы треугольника**
**Описание**: Создайте двумерный массив 5x5, где все элементы ниже главной диагонали равны 0.  
**Подсказка**: Используйте функцию `np.triu()`.

In [46]:
import numpy as np

a = np.random.randint(1, 10, size = (3))
b = np.triu(a)


print(b)


[[3 6 7]
 [0 6 7]
 [0 0 7]]


# Задание №11. **Сортировка массива**
**Описание**: Создайте массив из 8 случайных чисел и отсортируйте его по возрастанию.  
**Подсказка**: Используйте функцию `np.sort()`.

In [47]:
import numpy as np

a = np.random.randint(1, 10, size = (8))
print('Исходный массив:', a)
b = np.sort(a)
print('Отсортированный массив:', b)

Исходный массив: [3 2 7 7 4 1 8 8]
Отсортированный массив: [1 2 3 4 7 7 8 8]


# Задание №12. **Генерация линейно распределённых чисел**
**Описание**: Создайте массив из 10 чисел, равномерно распределённых между 0 и 1.  
**Подсказка**: Используйте функцию `np.linspace()`.

In [50]:
import numpy as np

print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# Задание №13. **Генерация случайных целых чисел**
**Описание**: Создайте случайный массив из 12 целых чисел от 1 до 100 и отсортируйте его по возрастанию.  
**Подсказка**: Используйте `np.random.randint()` и `np.sort()`.

In [52]:
import numpy as np

a = np.random.randint(1, 100, size = (12))
print('Исходный массив:', a)
b = np.sort(a)
print('Отсортированный массив:', b)

Исходный массив: [26 33 84 88 33 21  9 60 15 55 13 24]
Отсортированный массив: [ 9 13 15 21 24 26 33 33 55 60 84 88]


# Задание №14. **Сложение матриц поэлементно**
**Описание**: Создайте две матрицы 3x3 и сложите их поэлементно.  
**Подсказка**: Используйте операцию сложения `+`.

In [56]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print(a+b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


# Задание №15. **Случайные числа с заданным распределением**
**Описание**: Создайте массив из 10 случайных чисел с нормальным распределением.  
**Подсказка**: Используйте `np.random.randn()`.

In [59]:
import numpy as np
print(np.random.randn(10))

[ 1.14572616  1.31197275 -0.46113743 -0.69181562  0.04245084 -1.89559071
  1.34995362  0.96514597  0.61262279 -0.25647824]
