# Урок 4: Работа с модулем NumPy
Добро пожаловать на четвёртый урок по программированию на Python! Сегодня мы познакомимсся с библиотекой **NumPy**.
**NumPy** — это библиотека для языка Python, которая предоставляет удобные и быстрые способы работы с многомерными массивами и матрицами, а также содержит большое количество математических функций для работы с этими массивами. NumPy часто используется в научных вычислениях, анализе данных и машинном обучении.

# 1. Установка NumPy

Для начала работы с NumPy необходимо установить его, если он ещё не установлен. Для этого используйте команду:

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### После установки необходимо перезапустить ядро или просто закрыть-открыть VSCode.

# 2. Импорт библиотеки NumPy

После установки можно импортировать NumPy в программу:

In [1]:
import numpy as np

Здесь `np` — это общепринятое сокращение, чтобы не писать длинное `numpy` в каждой строке кода.

# 3. Основные возможности и функции NumPy

## 3.1. Основным объектом NumPy является **многомерный массив** — `ndarray` (n-dimensional array). Он отличается от стандартных списков Python тем, что:

- Все элементы имеют **одинаковый тип данных** (обычно числа).
- Он позволяет выполнять **векторные операции**, то есть операции над всеми элементами массива одновременно, что значительно ускоряет вычисления.
## Пример создания массивов

In [ ]:
import numpy as np

# Одномерный массив (из списка)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Двумерный массив (матрица)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# Из кортежа
b = np.array((4, 5, 6))
print(b)  # [4 5 6]




## Важные функции для создания массивов:

- **`np.zeros(shape, dtype=float)`**: Создаёт массив, заполненный нулями.

  ```python
  zeros_array = np.zeros((2, 3))
  print(zeros_array)
  # [[0. 0. 0.]
  #  [0. 0. 0.]]
  ```

- **`np.ones(shape, dtype=float)`**: Создаёт массив, заполненный единицами.

  ```python
  ones_array = np.ones((3, 2))
  print(ones_array)
  # [[1. 1.]
  #  [1. 1.]
  #  [1. 1.]]
  ```

- **`np.full(shape, fill_value, dtype=None)`**: Создаёт массив, заполненный заданным значением.

  ```python
  full_array = np.full((2, 2), 7)
  print(full_array)
  # [[7 7]
  #  [7 7]]
  ```

- **`np.eye(N, M=None, k=0, dtype=float)`**: Создаёт единичную матрицу (двумерный массив с единицами на главной диагонали).

  ```python
  identity_matrix = np.eye(3)
  print(identity_matrix)
  # [[1. 0. 0.]
  #  [0. 1. 0.]
  #  [0. 0. 1.]]
  ```

- **`np.arange(start, stop, step, dtype=None)`**: Аналогично встроенной функции `range()`, но возвращает массив.

  ```python
  arr = np.arange(0, 10, 2)
  print(arr)  # [0 2 4 6 8]
  ```

- **`np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)`**: Возвращает равномерно распределённые числа на заданном интервале.

  ```python
  linspace_arr = np.linspace(0, 1, 5)
  print(linspace_arr)  # [0.   0.25 0.5  0.75 1.  ]
  ```

### Параметры функций

- **`shape`**: Кортеж или список, определяющий размерность массива.
- **`dtype`**: Тип данных элементов массива (например, `int`, `float`, `complex`).
- **`start`**: Начальное значение последовательности.
- **`stop`**: Конечное значение последовательности (в `arange` не включается, в `linspace` по умолчанию включается).
- **`step`**: Шаг последовательности.
### Пример:

In [ ]:
import numpy as np

zeros_arr = np.zeros((3, 3))  # Массив из нулей 3x3
ones_arr = np.ones((2, 4))    # Массив из единиц 2x4
range_arr = np.arange(0, 10, 2)  # Чётные числа от 0 до 10
linspace_arr = np.linspace(0, 1, 5)  # 5 значений от 0 до 1

print(zeros_arr)
print(ones_arr)
print(range_arr)
print(linspace_arr)

## Типы данных в NumPy

NumPy поддерживает различные типы данных:

- **`int`**: Целые числа (`int8`, `int16`, `int32`, `int64`).
- **`float`**: Числа с плавающей точкой (`float16`, `float32`, `float64`).
- **`complex`**: Комплексные числа (`complex64`, `complex128`).
- **`bool`**: Логический тип данных (`True` или `False`).
- **`string`** и **`unicode`**: Строковые типы данных.

### Задание типа данных

При создании массива можно явно указать тип данных с помощью параметра `dtype`:

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  # float32

## 3.2. Индексация и срезы

NumPy позволяет легко получать доступ к элементам массива или его частям с помощью индексации и срезов.

### Пример индексации:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Получение элемента по индексу
print(arr[0])  # 10
print(arr[3])  # 40

### Пример срезов:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Получаем элементы с 2-го по 4-й (индексы 1, 2, 3)
print(arr[1:4])  # [2, 3, 4]

# Получаем элементы с 3-го до конца
print(arr[2:])  # [3, 4, 5, 6, 7]

### Логическая индексация

Можно использовать логические условия для выборки элементов массива.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Выбрать элементы больше 3
condition = arr > 3
print(condition)   # [False False False  True  True]
print(arr[condition])  # [4 5]

## 3.3. Изменение формы массива


### Функция `reshape()`

Метод **`reshape()`** позволяет изменить форму массива без изменения его данных.

```python
arr = np.arange(6)
print(arr)  # [0 1 2 3 4 5]

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# [[0 1 2]
#  [3 4 5]]
```

### Параметры функции `reshape()`

- **`newshape`**: Новая форма массива, заданная кортежем. Произведение размеров должно совпадать с числом элементов в массиве.

### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Превращаем одномерный массив в двумерный массив 2x3
reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)

## 3.4. Математические операции

NumPy поддерживает арифметические операции над массивами поэлементно.


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Сложение массивов
print(arr1 + arr2)  # [5 7 9]

# Умножение массива на число
print(arr1 * 2)  # [2 4 6]

# Возведение массива в степень
print(arr1 ** 2)  # [1 4 9]

### Универсальные функции (ufunc)

NumPy предоставляет большое количество математических функций, применяемых поэлементно.



### Параметры функций

- **`np.sin(x)`**: Синус каждого элемента массива `x`.
- **`np.cos(x)`**: Косинус каждого элемента массива `x`.
- **`np.exp(x)`**: Экспонента каждого элемента массива `x`.
- **`np.sqrt(x)`**: Квадратный корень каждого элемента массива `x`.
- **`np.log(x)`**: Натуральный логарифм каждого элемента массива `x`.

In [ ]:
arr = np.array([0, np.pi / 2, np.pi])

print(np.sin(arr))  # [0.000000e+00 1.000000e+00 1.224646e-16]
print(np.cos(arr))  # [ 1.000000e+00  6.123234e-17 -1.000000e+00]
print(np.exp(arr))  # [ 1.          4.81047738 23.14069263]

## 3.5. Операции с матрицами

NumPy предоставляет функции для выполнения матричных операций.

### Пример умножения матриц:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Матричное умножение
C = np.dot(A, B)
print(C)

## 3.6. Статистические функции

NumPy содержит много встроенных статистических функций.


### Основные функции

- **`np.min(a, axis=None)`**: Минимальное значение массива `a`.
- **`np.max(a, axis=None)`**: Максимальное значение массива `a`.
- **`np.mean(a, axis=None)`**: Среднее значение элементов массива `a`.
- **`np.median(a, axis=None)`**: Медиана элементов массива `a`.
- **`np.std(a, axis=None)`**: Стандартное отклонение элементов массива `a`.
- **`np.var(a, axis=None)`**: Дисперсия элементов массива `a`.
- **`np.sum(a, axis=None)`**: Сумма элементов массива `a`.



### Параметр `axis`

- **`axis=0`**: Операция выполняется по столбцам.
- **`axis=1`**: Операция выполняется по строкам.
### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Среднее значение
print(np.mean(arr))  # 3.0

# Стандартное отклонение
print(np.std(arr))  # 1.414

# Максимум и минимум
print(np.max(arr))  # 5
print(np.min(arr))  # 1


arr1 = np.array([[1, 2], [3, 4]])
print(np.sum(arr1, axis=0))  # [4 6]
print(np.sum(arr1, axis=1))  # [3 7]

## 3.7. Генерация случайных чисел


- **`np.random.rand(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из равномерного распределения на интервале [0, 1).

```python
random_arr = np.random.rand(3, 2)
print(random_arr)
```

- **`np.random.randn(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из стандартного нормального распределения.

```python
normal_arr = np.random.randn(3, 3)
print(normal_arr)
```

- **`np.random.randint(low, high=None, size=None, dtype=int)`**: Возвращает случайные целые числа из заданного интервала.

```python
int_arr = np.random.randint(1, 10, size=(2, 2))
print(int_arr)
```

### Параметры функций

- **`low`**: Нижняя граница (включительно).
- **`high`**: Верхняя граница (исключительно).
- **`size`**: Размер выходного массива.
- **`d0, d1, ..., dn`**: Размерности выходного массива.

### Пример:

In [2]:
random_arr = np.random.rand(3, 3)
print(random_arr)

random_int_arr = np.random.randint(1, 10, size=(2, 3))
print(random_int_arr)

normal_arr = np.random.randn(3, 3)
print(normal_arr)

[[0.96378206 0.87177143 0.98229712]
 [0.43556971 0.5656304  0.68631937]
 [0.65288572 0.09160212 0.392808  ]]
[[7 7 2]
 [7 1 7]]
[[-0.01256177 -0.51337175 -0.59110316]
 [ 0.02422629  0.89622877 -0.49134698]
 [-0.38665931 -0.42791214  2.46081699]]


## Линейная алгебра

NumPy содержит модуль `numpy.linalg` для выполнения операций линейной алгебры.


### Основные функции


- **`np.dot(a, b)`**: Матричное умножение массивов `a` и `b`.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
  
print(np.dot(a, b))
# [[19 22]
#  [43 50]]

- **`np.transpose(a)`** или `a.T`: Транспонирование массива `a`.

In [ ]:
print(a.T)
# [[1 3]
#  [2 4]]

- **`np.linalg.inv(a)`**: Обратная матрица для массива `a`.

In [ ]:
inv_a = np.linalg.inv(a)
print(inv_a)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

- **`np.linalg.det(a)`**: Детерминант массива `a`.

In [ ]:

det_a = np.linalg.det(a)
print(det_a)  # -2.0000000000000004

- **`np.linalg.eig(a)`**: Собственные значения и собственные векторы массива `a`.

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Собственные значения:", eigenvalues)
print("Собственные векторы:", eigenvectors)

#### Параметры функций

- **`a`, `b`**: Входные массивы (матрицы).
- **`axis`**: Ось, по которой выполняется операция.

# 4. Полезные функции и методы

### Функция `np.where(condition, [x, y])`

Возвращает элементы из `x`, где условие `condition` истинно, и элементы из `y` — где ложно.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

result = np.where(arr > 3, arr, 0)
print(result)  # [0 0 0 4 5]

### Функция `np.concatenate((a1, a2, ...), axis=0)`

Объединяет массивы вдоль указанной оси.


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

concat_arr = np.concatenate((a, b))
print(concat_arr)  # [1 2 3 4]

### Функция `np.unique(ar, return_counts=False)`

Находит уникальные элементы массива.
Если установить `return_counts=True`, то функция также вернёт количество вхождений каждого элемента.

In [ ]:
arr = np.array([1, 2, 2, 3, 3, 3])

unique_elements = np.unique(arr)
print(unique_elements)  # [1 2 3]

### Функция `np.triu(m,k)`

Функция numpy.triu (Triangle Upper) возвращает верхний треугольник двумерного массива или матрицы. Это означает, что она сохраняет элементы на главной диагонали и выше, а элементы ниже главной диагонали заменяет на нули (или на другое заданное значение).
### Параметры

- **`m`**: Входной массив или матрица, для которой нужно получить верхний треугольник.

- **`k`**: - Диагональ, относительно которой определяется верхний треугольник.
  - По умолчанию `k=0`, что означает главную диагональ.
  - `k > 0`: диагональ выше главной.
  - `k < 0`: диагональ ниже главной.


In [3]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Получаем верхний треугольник
upper_triangle = np.triu(a)

print("Оригинальная матрица:")
print(a)

print("\nВерхний треугольник матрицы:")
print(upper_triangle)

Оригинальная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Верхний треугольник матрицы:
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]



- **Документация NumPy**: [https://numpy.org/doc/](https://numpy.org/doc/)

# Задания для закрепления материала

# Задание №1. Нормализация массива с фильтрацией
**Описание**: Создайте массив случайных чисел размером 5x5. Затем отфильтруйте числа, которые больше среднего значения этого массива, и нормализуйте их так, чтобы сумма оставшихся элементов равнялась 1.


In [10]:
import numpy as np

a = np.random.randint(1,10,5*5).reshape(5,5)
print('Начальный массив:')
print(a)
print('Среднее значение массива:',np.mean(a))
b = np.where(a>np.mean(a), a, 0)
print('Отсортированный массив:')
print(b)
c = b/np.sum(b)
print('Отнормированный массив:')
print(c)
print('Сумма элементов отнормированного массива:',np.sum(c))

Начальный массив:
[[4 9 7 9 4]
 [9 2 5 3 1]
 [5 4 2 5 7]
 [9 2 4 6 4]
 [1 1 4 6 1]]
Среднее значение массива: 4.56
Отсортированный массив:
[[0 9 7 9 0]
 [9 0 5 0 0]
 [5 0 0 5 7]
 [9 0 0 6 0]
 [0 0 0 6 0]]
Отнормированный массив:
[[0.         0.11688312 0.09090909 0.11688312 0.        ]
 [0.11688312 0.         0.06493506 0.         0.        ]
 [0.06493506 0.         0.         0.06493506 0.09090909]
 [0.11688312 0.         0.         0.07792208 0.        ]
 [0.         0.         0.         0.07792208 0.        ]]
Сумма элементов отнормированного массива: 1.0


# Задание №2. Нахождение максимума в каждом ряду
**Описание**: Создайте двумерный массив размером 5x5 с произвольными числами. Пройдитесь по каждому ряду и найдите максимальное значение. Если максимальное значение больше 10, замените все элементы этого ряда на 1.

In [23]:
import numpy as np

a = np.random.randint(1,20,5*5).reshape(5,5)
print('Начальный массив:')
print(a)

for i in range(len(a)):
    m = np.max(a[i])
    print(f'Макимальное значение в {i} ряду: {m}')
    if (m > 10):
        print(f'Замена всех элементов {i} ряда на 1')
        a[i] = np.ones(5)
print(a)
          


Начальный массив:
[[ 8 14 19 18  7]
 [14 14  1 11 18]
 [17 15  6  9 10]
 [ 8 12 18  6  7]
 [ 3  9  6  6  6]]
Макимальное значение в 0 ряду: 19
Замена всех элементов 0 ряда на 1
Макимальное значение в 1 ряду: 18
Замена всех элементов 1 ряда на 1
Макимальное значение в 2 ряду: 17
Замена всех элементов 2 ряда на 1
Макимальное значение в 3 ряду: 18
Замена всех элементов 3 ряда на 1
Макимальное значение в 4 ряду: 9
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [3 9 6 6 6]]


# Задание №3. Создание симметричной матрицы
**Описание**: Создайте случайную матрицу 4x4 и преобразуйте её в симметричную (где элемент [i, j] равен элементу [j, i]). Если элемент на диагонали меньше 0, замените его на 0.

In [29]:
import numpy as np

a = np.random.randint(-10,10,4*4).reshape(4,4)
print('Начальная матрица:')
print(a)

for i in range(len(a)):
    for j in range(i,len(a)):
        a[i][j] = a[j][i]
        if i == j and a[i][j] <0: a[i][j] = 0
print('Итоговая матрица:')
print(a)

Начальная матрица:
[[ -8   2  -7   9]
 [ -7 -10   9  -8]
 [-10   2 -10   9]
 [ -7   3   5   1]]
Итоговая матрица:
[[  0  -7 -10  -7]
 [ -7   0   2   3]
 [-10   2   0   5]
 [ -7   3   5   1]]


# Задание №4. Кумулятивная сумма с проверкой
**Описание**: Создайте массив из 10 случайных чисел. Рассчитайте кумулятивную сумму. Если на каком-либо шаге кумулятивная сумма превышает 50, прекратите вычисления и выведите позицию, на которой произошло превышение.

In [35]:
import numpy as np

a = np.random.randint(1,10, 10)
print('Начальный массив:',a)

sum = 0
for i in range(len(a)):
    sum += a[i]
    if sum > 50:
        print(f'Сумма превысила 50 на {i+1} шаге: a[{i}] = {a[i]}')
        print('Значение суммы на этом шаге равно:', sum)
        break
else:
    print('Кумулятивная сумма:', sum)

Начальный массив: [5 3 8 4 4 5 2 3 2 7]
Кумулятивная сумма: 43


# Задание №5. Создание единичной матрицы с модификацией
**Описание**: Создайте единичную матрицу размером 5x5. Если элемент на главной диагонали является нечётным числом, замените его на 2.

In [ ]:
import numpy as np

i = np.eye(5, dtype=np.int8)
print('Исходная матрица:')
print(i)

for k in range(len(i)):
    if i[k][k] % 2 != 0: 
        i[k][k] = 2

print('Итоговая матрица:')
print(i)

Исходная матрица:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Итоговая матрица:
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]


# Задание №6. Матричное умножение с проверкой
**Описание**: Создайте две случайные матрицы 3x3 и выполните их матричное умножение. Если сумма любого столбца в результирующей матрице больше 15, замените все элементы этого столбца на -1.

In [59]:
import numpy as np

a = np.random.randint(-5,5,(3,3))
print('Матрица А:')
print(a)
b = np.random.randint(-5,5,(3,3))
print('Матрица B:')
print(b)

res = np.dot(a,b)
print('AxB:')
print(res)

for i in range(len(res)):
    if np.sum(res[:,i]) > 15: res[:,i] = -1
print('После проверки:')
print(res)

Матрица А:
[[-3 -2 -4]
 [ 0  4  4]
 [-3 -2 -1]]
Матрица B:
[[-5 -2  1]
 [-1  4 -5]
 [-4 -5 -2]]
AxB:
[[ 33  18  15]
 [-20  -4 -28]
 [ 21   3   9]]
После проверки:
[[ -1  -1  15]
 [ -1  -1 -28]
 [ -1  -1   9]]


# Задание №7. Нахождение уникальных значений с фильтрацией
**Описание**: Создайте массив случайных чисел. Найдите уникальные элементы. Если количество уникальных элементов больше 10, удалите все числа, которые больше 50.

In [68]:
import numpy as np

a = np.random.randint(1,100, 100)
print('Исходный массив:')
print(a)

b = np.unique(a)

if len(b) > 10:
    c = b<50
    b = b[c]
print('Уинкальные значения (отфильтрованные):')
print(b)

Исходный массив:
[13 97 90 69 67 67 82  9 84 83  2 42 39 58 20 83 97 21 90 52 61 17  7 22
 89 67 14 45 32 94 92 58 76 49 84 29 28 31 30 88 40 32 68 34 32 27 93 66
 55 51 43 15 36 63  9 71 39 65 53 34 65 41 63 61 68 35 37 99 56 49  5 14
 16 93 55 91 29 89 80 33 35 99 26 62 85 41 42 97 29  2 91  3 85 36 50 70
  8 25 28  9]
Уинкальные значения (отфильтрованные):
[ 2  3  5  7  8  9 13 14 15 16 17 20 21 22 25 26 27 28 29 30 31 32 33 34
 35 36 37 39 40 41 42 43 45 49]


# Задание №8. Модификация массива на основе медианы
**Описание**: Создайте массив случайных чисел размером 1x10. Найдите медиану массива. Если число больше медианы, умножьте его на 2, если меньше — поделите на 2.

In [12]:
import numpy as np

a = np.random.rand(10)*10
print('Изначальный массив:',a)

c = np.median(a)
s = ''

for i in range(len(a)):
    if a[i]>c: a[i] *= 2
    elif a[i]<c: a[i] /=2
    s += f'{a[i]:.2f} '
print('Итоговый массив:', s) 


Изначальный массив: [9.03461394 9.43393586 1.13856817 0.69205669 2.94183249 9.00098451
 7.68973416 0.45201924 4.63638918 7.77393094]
Итоговый массив: 18.07 18.87 0.57 0.35 1.47 18.00 15.38 0.23 2.32 15.55 


# Задание №9. Отбор элементов с фильтрацией и умножением
**Описание**: Создайте двумерный массив размером 5x5. Отберите все элементы, которые являются чётными и больше среднего значения массива, и умножьте их на 3.

In [ ]:
import numpy as np

a = np.random.randint(1,10,(5,5))
print('Исходная матрица:')
print(a)
c = np.mean(a)
print('Среднее значение:',c)
a = np.where(a%2 == 0, a,0)
b = np.where( a > c, a, 0)
print('Итоговый массив:')
print(b)

Исходная матрица:
[[1 2 9 9 1]
 [4 5 5 9 9]
 [1 9 2 8 7]
 [6 2 4 7 6]
 [6 7 7 5 2]]
Среднее значение: 5.32
Итоговый массив:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 8 0]
 [6 0 0 0 6]
 [6 0 0 0 0]]


# Задание №10. Поэлементное сложение с условиями
**Описание**: Создайте два одномерных массива по 10 элементов каждый. Выполните поэлементное сложение. Если сумма элементов на каком-то шаге превышает 10, замените этот элемент на 0.

In [43]:
import numpy as np

a = np.random.randint(1,10,10)
print('Массив:',a)
b = np.random.randint(1,10,10)
print('Массив:',b)

res = np.where(a + b > 10, 0, a + b)
print(res)

Массив: [1 9 7 7 5 3 6 7 4 7]
Массив: [5 1 7 1 6 6 5 5 4 2]
[ 6 10  0  8  0  9  0  0  8  9]


# Задание №11.  Сортировка и фильтрация массива
**Описание**: Создайте массив случайных чисел. Отсортируйте его по возрастанию. Затем найдите все элементы, которые меньше среднего значения массива, и замените их на 0.

In [52]:
import numpy as np

a = np.random.randint(1,100,100)
print('Исходный массив:')
print(a)
a.sort()
print('Отсортированный массив:',)
print(a)

c = np.mean(a)
print('Среднее значение:',c)
a = np.where(a>=c, a, 0)
print('Фильтрация:')
print(a)

Исходный массив:
[ 7 84 99 36 33 77 23 15 23 22 99 10 74 67 70 89 57 62 50 69 81  7 70 48
 37 49 96 98 87 99 80 63 32 50 12  2  3 49 53  5 28 96 32  7 10 52  8 80
  5 69 33  2 79 64 76 39 58 74 18 56 79  4 29 80 31 46 96  4  4 33 71 69
 54 78 87 89 67  6 28 58 69 37 87 51 31 31 69  3 49 54 57 79 74 34 37 44
 82 81 30 39]
Отсортированный массив:
[ 2  2  3  3  4  4  4  5  5  6  7  7  7  8 10 10 12 15 18 22 23 23 28 28
 29 30 31 31 31 32 32 33 33 33 34 36 37 37 37 39 39 44 46 48 49 49 49 50
 50 51 52 53 54 54 56 57 57 58 58 62 63 64 67 67 69 69 69 69 69 70 70 71
 74 74 74 76 77 78 79 79 79 80 80 80 81 81 82 84 87 87 87 89 89 96 96 96
 98 99 99 99]
Среднее значение: 50.24
Фильтрация:
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0 51 52 53 54 54 56 57 57 58 58 62 63 64 67 67 69 69 69 69 69 70 70 71
 74 74 74 76 77 78 79 79 79 80 80 80 81 81 82 84 87 87 87 89 89 96 96 96
 98 99 99 99]


# Задание №12.  Транспонирование с модификацией
**Описание**: Создайте двумерный массив 3x3. Транспонируйте его и замените все элементы, которые больше 5, на их логарифмы.

In [53]:
import numpy as np

a = np.random.randint(1,10,(3,3))
print('Исходный массив:')
print(a)

a = np.transpose(a)
a = np.where( a>5, np.log(a) , a)
print('Транспонированная матрица с модификацией:')
print(a)

Исходный массив:
[[8 3 6]
 [5 9 6]
 [5 1 3]]
Транспонированная матрица с модификацией:
[[2.07944154 5.         5.        ]
 [3.         2.19722458 1.        ]
 [1.79175947 1.79175947 3.        ]]


# Задание №13.  Обратная матрица с проверкой
**Описание**: Создайте случайную матрицу 3x3. Найдите её обратную матрицу. Если сумма какого-либо ряда в обратной матрице больше 10, умножьте этот ряд на 2.

In [63]:
import numpy as np

a = np.random.rand(3,3)
print('Исходный массив:')
print(a)

a = np.linalg.inv(a)
for i in range(len(a)):
    if np.sum(a[i]) > 10:
        a[i] *= 3
print('Итоговая обратная матрица')
print(a)

Исходный массив:
[[0.32809562 0.43399065 0.96614595]
 [0.23810162 0.07560327 0.13326926]
 [0.9903971  0.99222059 0.37407284]]
Итоговая обратная матрица
[[-0.74023204  5.6703077  -0.10828239]
 [ 0.30564619 -5.93984045  1.32674507]
 [ 1.14912173  0.74257113 -0.55919913]]


# Задание №14. Перемешивание с модификацией
**Описание**: Создайте массив из 10 чисел. Перемешайте элементы массива случайным образом. Если в новом массиве есть числа больше 5, уменьшите их на 3.

In [69]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.random.shuffle(a)
print('Перемешанный массив:', a)

a = np.where(a>5, a-3, a)
print('Итоговый массив:', a)


Перемешанный массив: [ 1  7  8  2 10  6  5  4  3  9]
Итоговый массив: [1 4 5 2 7 3 5 4 3 6]


# Задание №15.  Цикл с вложенным условием
**Описание**: Создайте двумерный массив 4x4. Для каждого элемента массива выполните следующее: если элемент чётный, возведите его в квадрат, если нечётный — умножьте на 2.

In [70]:
import numpy as np

a = np.random.randint(1,10, (4,4))
print('Исходный массив:')
print(a)

a = np.where(a%2, a*2, a**2)
print('Итоговый массив:')
print(a)

Исходный массив:
[[8 8 6 6]
 [8 7 5 6]
 [4 7 9 9]
 [5 1 5 5]]
Итоговый массив:
[[64 64 36 36]
 [64 14 10 36]
 [16 14 18 18]
 [10  2 10 10]]
